### ISSUE TITLE
Storing of credentials in browser client.

### ISSUE THREAD

**Issue by yalamber** [hueniverse/hawk#138]
Hello, 
I am a bit confused on how to store credentials data in browser once I get from Server. Is it fine storing credentials data once I get from server in plain text in localstorage or cookie?

**Comment by jzorn** [comment]
Yep.

**Comment by hueniverse** [comment]
You can use local storage (I believe it will block XSS access). As for cookies, you can store it but only in secure cookies with properly limited scope. I would avoid using cookies for it. If you can't use local storage, use a cookie auth scheme to first authenticate the client, then exchange it for a token per session.

**Comment by jzorn** [comment]
Also, consider that you can only store 4093 bytes in your cookies.

**Comment by taoeffect** [comment]
Cookies are sent with every request right? So I think that would defeat the purpose of Hawk.

However, thinking it through more, I think Hawk's security is no different from cookies anyway since the server sends `hawk/browser.js` on every request as well, meaning that a MITM can still grab the credentials from localStorage.

Because of that, I don't think Hawk can be a very meaningful improvement over cookies until it has native browser support for storing the credentials.

Also, credentials storage should be mentioned at least somewhere in the docs. I find it very odd that the word `localStorage` doesn't appear anywhere them.

**Comment by taoeffect** [comment]
I've given this some more thought, and have noticed one advantage of Hawk's approach over cookies, which is persistence. The option to use `localStorage` (which doesn't exist with cookies), means that the credentials are more long-lived/persistent. Most browsers make it relatively trivial to clear out or delete cookies, but so far at least it seems `localStorage` isn't as easy to reset (and not something most users probably think of).
