### ISSUE TITLE
How does Hawk prevent CSRF attacks, session fixation? 

### ISSUE THREAD

**Issue by makerofthings7** [hueniverse/hawk#204]
OAuth and many other authentication protocols have a cookie handshake that sets a secret value in the HTTP only cookies.

There are a few other ways to manage this, but this seems to be the most common mitigation.

How does Hawk mitigate this risk?

**Comment by Dreyer** [comment]
I'm not sure I understand your particular use case for Hawk. Maybe you can provide a little more context?

Do you happen to be using the Hawk [lib/browser.js](https://github.com/hueniverse/hawk/blob/master/lib/browser.js) script?

Otherwise, is the following FAQ might be helpful: [Does Hawk have anything to do with OAuth?](https://github.com/hueniverse/hawk#does-hawk-have-anything-to-do-with-oauth)

> [ ... ] 
>
> Hawk provides a simple HTTP authentication scheme for making client-server requests. It does not address the OAuth use case of delegating access to a third party. If you are looking for an OAuth alternative, check out [Oz](https://github.com/hueniverse/oz).

In particular the distinction between *"making **client-server** requests"* (Hawk) vs. *"delegating access to a third party"* (OAuth).

**Comment by makerofthings7** [comment]
I'll ask differently.

Suppose example.com uses hawk. The user is already logged into example.com

Then spamsite.com/hack creates an iFrame with example.com in it... the user navigates to this page.

Does hawk's authentication remain logged in while in an iFrame?  This is one (of many examples) in which a CSRF attack could occur, and it's usually mitigated with bearer tokens.  

I'm looking at the hawk protocol, and haven't implemented it. Just seeing if it meets the security requirements before using it. 

PS- I'll look at OZ as well. Thanks

**Comment by hueniverse** [comment]
Hawk is a simple client-server auth protocol. It has no state. Your question is irrelevant to this protocol as it is completely up to you on how you implement your own site state.
